@echo off

echo Compiling main.js ...
java -jar closure-compiler-v20220719.jar --js scripts\main.js --js_output_file scripts\main.min.js
echo Compiling maps.js ...
java -jar closure-compiler-v20220719.jar --js scripts\maps.js --js_output_file scripts\maps.min.js
echo Compiling compact.js ...
java -jar closure-compiler-v20220719.jar --js scripts\compact.js --js_output_file scripts\compact.min.js
